---
title: "Assignment 1: Introduction"
author: "Tori Newton"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took an undergrad course on experimental methods in organismal biology where we used R and Git to analyze various data sets. That is my only previous experience and I have not used R or Git since that course.

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident in my ability to keep up with the lectures, course material, and follow instructions for assignments.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am apprehensive about my current skill level with R and Git as I am not confident in my current level of knowledge. I hope to learn more in this course and build confidence and comfort with R and Git.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
